"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.$room = exports.$limitcam = exports.$kv = exports.$callback = void 0;
const _callback_1 = require("./api/$callback");
Object.defineProperty(exports, "$callback", { enumerable: true, get: function () { return _callback_1.$callback; } });
const _kv_1 = require("./api/$kv");
Object.defineProperty(exports, "$kv", { enumerable: true, get: function () { return _kv_1.$kv; } });
const _limitcam_1 = require("./api/$limitcam");
Object.defineProperty(exports, "$limitcam", { enumerable: true, get: function () { return _limitcam_1.$limitcam; } });
const _room_1 = require("./api/$room");
Object.defineProperty(exports, "$room", { enumerable: true, get: function () { return _room_1.$room; } });
require("./sharedCode");
